version: '3'
services:

  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    container_name: 'gitlab-services'
    restart: always
    hostname: 'gitlab.dev.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.dev.com'
        GITLAB_ROOT_EMAIL="root@local"
        GITLAB_ROOT_PASSWORD="Redhat123"
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
      - '587:587'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: 'jenkins-service'
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins-volume:/var/jenkins_home'

  nexus:
    image: 'sonatype/nexus3:latest'
    container_name: 'nexus-service'
    restart: always
    ports:
      - '8081:8081'
    volumes:
      - nexus-volume:/nexus-data

volumes:
  jenkins-volume:
  nexus-volume: